name: synergy_sphere
description: SynergySphere mobile MVP
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  go_router: ^14.2.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true 
  assets:
    - .env


  